---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 30
        javascript:
        python:
        php:
    exclude_fingerprints:
  fixme:
    enabled: true
    exclude_fingerprints:
  rubocop:
    enabled: true
    exclude_fingerprints:
ratings:
  paths:
  - Gemfile.lock
  - "**.js"
  - "**.rb"
exclude_paths:
- config/
- db/
- spec/
- vendor/
