---
engines:
  bundler-audit:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 30
        javascript:
        python:
        php:
    exclude_fingerprints:
    - c1602d46125c5d6c015c56d6bc5f6b9d
  fixme:
    enabled: true
    exclude_fingerprints:
  rubocop:
    enabled: true
#    exclude_fingerprints:
ratings:
  paths:
  - Gemfile.lock
  - "**.js"
  - "**.rb"
exclude_paths:
- config/
- db/
- spec/
- vendor/
