language: php

php:
  - 7.1

addons:
  code_climate:
    repo_token: $code_climate_token

install:
  - composer install
  - vendor/bin/security-checker security:check --end-point=http://security.sensiolabs.org/check_lock

after_success:
  - vendor/bin/test-reporter
